### ISSUE TITLE
interested in giving a hand

### ISSUE THREAD

**Issue by Tayran** [Elfocrash/L2jRoboto#1]
You said you needed a hand, what needs to be done now?

**Comment by Elfocrash** [comment]
A TON of features are missing and I will have to make a list. I think for now adding all the classes (except summoners) is my next priority.

**Comment by Elfocrash** [comment]
@Tayran Unless you wanna as something else, i will close this. Is that ok?

**Comment by LeonanCarvalho** [comment]
@Tayran  It could be useful for l2jbrasil project, for "//playerspawn" command  :)

https://www.l2jbrasil.com/index.php?/topic/124761-l2jroboto-a-fake-player-engine/&do=findComment&comment=771568

**Comment by Elfocrash** [comment]
@LeonanCarvalho Would be a good idea. However you have to keep it in sync with this project as it is nowhere near a ready state
